#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "52.8.245.166";
$SERVER_PORT = 42951;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
